In [0]:
## libraries used tensorflow  2.0 or above and keras

In [0]:
from tensorflow.keras.preprocessing.text import one_hot

In [0]:
## sentences
sent=['the glass of milk','the glass of guice','the cup of tea','iam a boy','iam a developer','understood the meaning of words','your videos are good',]

In [11]:
sent

['the glass of milk',
 'the glass of guice',
 'the cup of tea',
 'iam a boy',
 'iam a developer',
 'understood the meaning of words',
 'your videos are good']

In [0]:
voc_size=10000

In [0]:
onehot_repr=[one_hot(words,voc_size) for words in sent]


In [18]:
print(onehot_repr
      )

[[9301, 6475, 3089, 2833], [9301, 6475, 3089, 4945], [9301, 1580, 3089, 4882], [9557, 1774, 7960], [9557, 1774, 125], [8964, 9301, 2554, 3089, 3771], [7332, 723, 499, 1577]]


In [0]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

word embedding
[link text](https://)

In [0]:
import numpy as np


In [0]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)

In [24]:
print(embedded_docs)

[[   0    0    0    0 9301 6475 3089 2833]
 [   0    0    0    0 9301 6475 3089 4945]
 [   0    0    0    0 9301 1580 3089 4882]
 [   0    0    0    0    0 9557 1774 7960]
 [   0    0    0    0    0 9557 1774  125]
 [   0    0    0 8964 9301 2554 3089 3771]
 [   0    0    0    0 7332  723  499 1577]]


In [0]:
dim=10

In [0]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')


In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [28]:
print(model.predict(embedded_docs))

[[[ 2.15887763e-02 -3.58269103e-02  4.75795530e-02 -8.00082833e-03
    2.34027617e-02 -1.00881942e-02  9.73298401e-03 -3.58875170e-02
    4.32855226e-02 -4.67598550e-02]
  [ 2.15887763e-02 -3.58269103e-02  4.75795530e-02 -8.00082833e-03
    2.34027617e-02 -1.00881942e-02  9.73298401e-03 -3.58875170e-02
    4.32855226e-02 -4.67598550e-02]
  [ 2.15887763e-02 -3.58269103e-02  4.75795530e-02 -8.00082833e-03
    2.34027617e-02 -1.00881942e-02  9.73298401e-03 -3.58875170e-02
    4.32855226e-02 -4.67598550e-02]
  [ 2.15887763e-02 -3.58269103e-02  4.75795530e-02 -8.00082833e-03
    2.34027617e-02 -1.00881942e-02  9.73298401e-03 -3.58875170e-02
    4.32855226e-02 -4.67598550e-02]
  [-8.95937532e-03  2.79461220e-03 -1.52351707e-03 -4.52718996e-02
   -3.06229237e-02  3.68695334e-03 -3.24751511e-02 -1.41806491e-02
    2.36009695e-02 -8.69510323e-03]
  [ 2.12141760e-02  3.35345902e-02 -4.61692810e-02  2.22907402e-02
    1.03848465e-02  4.59965579e-02  9.80617851e-03 -1.67614818e-02
   -1.42088160e-

In [29]:
embedded_docs[0]

array([   0,    0,    0,    0, 9301, 6475, 3089, 2833], dtype=int32)

In [30]:
print(model.predict(embedded_docs)[0])

[[ 0.02158878 -0.03582691  0.04757955 -0.00800083  0.02340276 -0.01008819
   0.00973298 -0.03588752  0.04328552 -0.04675986]
 [ 0.02158878 -0.03582691  0.04757955 -0.00800083  0.02340276 -0.01008819
   0.00973298 -0.03588752  0.04328552 -0.04675986]
 [ 0.02158878 -0.03582691  0.04757955 -0.00800083  0.02340276 -0.01008819
   0.00973298 -0.03588752  0.04328552 -0.04675986]
 [ 0.02158878 -0.03582691  0.04757955 -0.00800083  0.02340276 -0.01008819
   0.00973298 -0.03588752  0.04328552 -0.04675986]
 [-0.00895938  0.00279461 -0.00152352 -0.0452719  -0.03062292  0.00368695
  -0.03247515 -0.01418065  0.02360097 -0.0086951 ]
 [ 0.02121418  0.03353459 -0.04616928  0.02229074  0.01038485  0.04599656
   0.00980618 -0.01676148 -0.01420882 -0.04558346]
 [-0.04866507  0.04136674 -0.02279013 -0.03812263 -0.02466958 -0.03633028
   0.02020133  0.04196284 -0.03489268 -0.03739931]
 [ 0.03524568 -0.00482636  0.01312571  0.02820984 -0.0134111  -0.04497266
  -0.04313674 -0.01502101 -0.02303492  0.01371649]]